[package]
name = "mazes"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.4"
rand = "0.8.5"

[[bin]]
name = "binary_tree"
path = "demos/binary_tree.rs"

[[bin]]
name = "sidewinder"
path = "demos/sidewinder.rs"
